// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: gamemodes.sql

package store

import (
	"context"
)

const insertGamemodes = `-- name: InsertGamemodes :exec
INSERT INTO gamemodes (id, name)
VALUES (?, ?)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name
`

type InsertGamemodesParams struct {
	ID   int64
	Name string
}

func (q *Queries) InsertGamemodes(ctx context.Context, arg InsertGamemodesParams) error {
	_, err := q.db.ExecContext(ctx, insertGamemodes, arg.ID, arg.Name)
	return err
}
