// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: matches.sql

package store

import (
	"context"
)

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (created_at)
VALUES (date('now'))
RETURNING id, created_at
`

func (q *Queries) CreateMatch(ctx context.Context) (Match, error) {
	row := q.db.QueryRowContext(ctx, createMatch)
	var i Match
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
