// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: matches.sql

package store

import (
	"context"
	"time"
)

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (gamemode_id, created_at)
VALUES (?, date('now'))
RETURNING id, created_at
`

type CreateMatchRow struct {
	ID        int64
	CreatedAt time.Time
}

func (q *Queries) CreateMatch(ctx context.Context, gamemodeID int64) (CreateMatchRow, error) {
	row := q.db.QueryRowContext(ctx, createMatch, gamemodeID)
	var i CreateMatchRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
