// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"time"
)

type Match struct {
	ID        int64
	CreatedAt time.Time
}

type Player struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    time.Time
}
